"""added title to Session

Revision ID: 38d7caebf456
Revises: 1bb04b7989ac
Create Date: 2024-12-11 15:33:40.109976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d7caebf456'
down_revision: Union[str, None] = '1bb04b7989ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE session SET title = \'Chat Session\' WHERE title IS NULL')
    op.alter_column('session', 'title', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'title')
    # ### end Alembic commands ###
